SRC =main.c \
addition.c \
cube.c \
division.c \
factorial.c \
modulus.c \
multiplication.c \
modulus.c \
power.c \
square.c \
squareroot.c \
subtraction.c \
Percentage_of_Profit_or_Loss.c 

INC = Header.h

target : $(SRC) $(INC)
	gcc $(SRC) -o a.out
